// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using REVOPS.DevChallenge.Context;

#nullable disable

namespace REVOPS.DevChallenge.Migrations
{
    [DbContext(typeof(ContextoBanco))]
    partial class ContextoBancoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("REVOPS.DevChallenge.Context.Entities.ChatInfo", b =>
                {
                    b.Property<string>("ChatId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnyAttendantAssigned")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId");

                    b.ToTable("ChatInfos");
                });

            modelBuilder.Entity("REVOPS.DevChallenge.Context.Entities.RegistroDeChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveBotName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveBotStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ChatCreatedAtUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatTags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAtUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ContactIsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactProfilePictureUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactTags")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullHistoryJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnyAttendantAssigned")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWaiting")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastMessageAtUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastMessageContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastMessageSource")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SearchedAtUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("SectorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SectorName")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalAIResponses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalUnread")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WaitingSinceUTC")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SearchedAtUTC");

                    b.ToTable("RegistroDeChats");
                });
#pragma warning restore 612, 618
        }
    }
}
